### ISSUE TITLE
Server Doesn't Start

### ISSUE THREAD

**Issue by IAmSneak** [Gunpowder-MC/GunpowderUtilities#1]
Fabric 1.16.2 Server
Mods: Fabric API, Gunpowder Base, Gunpowder Utilities, Fabric Language Kotlin

Didn't generate crash report. Here is the log:
[latest.log](https://github.com/Gunpowder-MC/GunpowderUtilities/files/5177642/latest.log)

**Comment by Martmists-GH** [comment]
You're missing PlayerAbilityLib
