### ISSUE TITLE
Downloading the mod

### ISSUE THREAD

**Issue by ghost** [Gunpowder-MC/GunpowderUtilities#20]
Hey! Sorry if this is the wrong place to ask but how do i actually get the mod? I'm new to github so i may just be blind but the only thing i can download is a .zip file

**Comment by irunatbullets** [comment]
Use a launcher like [gdlauncher](https://gdevs.io/). You can then just search for the pack by clicking the plus symbol > twitch > then search 'all of fabric'.

**Comment by ghost** [comment]
Oh cool! is this the latest version? (1.0.3) as im trying to get disguiseLib to work along side gunpowder so i thought you were able to download the mod similar to curseforge

**Comment by irunatbullets** [comment]
I'd say that's the latest.

Once you've installed the pack you can right-click the pack, manage instance, click 'mods' on the left then look for a button that says 'add mods'. It'll show you what's compatible with the version of Minecraft the pack is using. If there things you're looking for are available you can add them, but just remember that mods can potentially conflict with each other - so adding one at a time is probably a good idea. Gunpowder should be fine as is used in the official servers, but I'm not sure about the other one - give it a go.

**Comment by ghost** [comment]
Awesome thank you!
