### ISSUE TITLE
Incompatibility with Carpet /player

### ISSUE THREAD

**Issue by ghost** [Gunpowder-MC/GunpowderUtilities#21]
Please can you fix the incompatibility that happens when using this(and the gunpowder base) with [Carpet](https://github.com/gnembon/fabric-carpet)?

**Comment by Martmists-GH** [comment]
Carpet is known to break many mods and thus not supported. If you give a crash log I can take a look, but otherwise I can't do anything.

**Comment by ghost** [comment]
From experience it hasn't broken any mods that I've used. LuckPerms broke Carpet.
However, I can't give you a log so I'll close this.
Sorry for a late response.
