### ISSUE TITLE
When I vanish, I am still visible in the server listing

### ISSUE THREAD

**Issue by ghost** [Gunpowder-MC/GunpowderUtilities#5]
Is there any way for this to be fixed?

**Comment by Martmists-GH** [comment]
What server listing do you mean?

**Comment by samolego** [comment]
> What server listing do you mean?

Probably in multiplayer screen (server selector). If you hover over the player count, it shows all the players.

**Comment by ghost** [comment]
> Probably in multiplayer screen (server selector). If you hover over the player count, it shows all the players.

Yes, this is what I mean.
